# Generated by Django 6.0.2 on 2026-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0008_auth_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smsalert',
            name='target',
            field=models.CharField(default='all', help_text='all / state:Punjab / crop:wheat', max_length=50),
        ),
    ]
